### ISSUE TITLE
Does ROMS support domains which cross the Greenwich Meridian?

### ISSUE THREAD

**Issue by TomNicholas** [CESR-lab/ucla-roms#1]
Does ROMS support domains which cross the Greenwich Meridian?

@sdbachman and I were unsure, but after we noticed that the MATLAB tools don't seem to generate a sensible grid for this case, we've just been avoiding trying running any domains which do cross. At the moment in the new python version of the setup tools I have just forbidden this case (see https://github.com/CWorthy-ocean/roms-tools/issues/3), but it would be nice to know if it's something that should be supported or something that we are definitely not supporting.

**Comment by nmolem** [comment]
We totally should support it and some of the tools have (had) provisions to deal with that, but it might need some fresh attention as our recent work has exclusively been in the Pacific. ROMS itself has no awareness of latitude at all, but the atmospheric (and tidal) forcing pre-processing tools do. It's not a big deal, but like everything, it's represents work.

**Comment by nmolem** [comment]
I added this functionality in our pre-processing tools and am closing the issue.
