### ISSUE TITLE
Latest changes have "broken" (easily fixed) `Flux_frc` example

### ISSUE THREAD

**Issue by dafyddstephenson** [CESR-lab/ucla-roms#13]
Hi all,
The latest version of [`flux_frc.opt`](https://github.com/CESR-lab/ucla-roms/blob/main/src/flux_frc.opt)
has changed the value of `tname` to 'time' for every variable, but the forcing files in the `Flux_frc` example do not reflect this.
This can be fixed by either changing the `tname` strings back, or by adding a `flux_frc.opt` file to `Example/Flux_frc` with the correct names for the example. 

The problem could also by fixed by changing the netcdf files, though I wouldn't recommend this as it could bloat the repo by keeping the old ones in its history. 

Just wanted to flag it up as it'll affect the automated testing down the line.
Thanks!
Dafydd

(EDIT: This also affects `Pipes_real` and `Rivers_real` )

**Comment by nmolem** [comment]
Thanks Davydd. I had 'older' option files in the examples that had the different time variables for the different variables in each example directory, overriding the 'newer' versions that have a single time variable for all. I need to clean this up.
