### ISSUE TITLE
cpp check missing from `bgc.F`

### ISSUE THREAD

**Issue by dafyddstephenson** [CESR-lab/ucla-roms#19]
Hi all,
we've noticed that when compiling without `AVERAGES` that certain parts of the code are being reached that shouldn't be.
This can be fixed by:
- adding `#ifdef AVERAGES` at line 270 with a corresponding `#endif` at line 316
- changing `#if defined(BEC2_DIAG) || defined(MARBL_DIAGS)` on line 491 to `#if (defined(BEC2_DIAG) || defined(MARBL_DIAGS)) && defined(AVERAGES)`

**Comment by dafyddstephenson** [comment]
While there is a check for `avg`, this is a different switch, and a user can reach undefined variables and routines if they run accidentally with `avg` but without `AVERAGES`. This should act as a failsafe.

**Comment by nmolem** [comment]
We removed all instances of the AVERAGES cpp key and use the logicals from the option file.

**Comment by dafyddstephenson** [comment]
That sounds like a better long-term solution, thanks for going through that. Could you push the changes in order to close the issue? Thanks.

**Comment by dafyddstephenson** [comment]
thanks - will test this out tomorrow and close this down
