### ISSUE TITLE
Missing variables in IC file not properly initialised to 0

### ISSUE THREAD

**Issue by dafyddstephenson** [CESR-lab/ucla-roms#3]
Hi all,
In `get_init.F`, specifically at lines 464 and 541, entries in `t`, and `bec2_diag_3d` respectively are supposed to be set to 0 in the event that variables are missing from the IC/restart file. However this is only done in one layer, e.g. `bec2_diag_3d(GLOBAL_2D_ARRAY,1,itrc) = 0.0`. I believe the `1` here should be a `:`.

**Comment by nmolem** [comment]
Thanks @dafyddstephenson 
I removed the bec2_diag things from get_init since there is not need to initialize diagnostics, but I fixed the zero init of tracer fields for which there are no data in the init file.

Closing the issue
