### ISSUE TITLE
inconsistency between module name and filename

### ISSUE THREAD

**Issue by dafyddstephenson** [CESR-lab/ucla-roms#8]
Hi all, 
I noticed that the module `work_mod` is contained in a file `work.F`, which is leading to problems with my local dependency generator. Apparently the module used to be called `work` but was renamed to fix a clash. It seems the filename was not updated too, though the filename=module name convention is present elsewhere in the code with this one exception.

Could you rename `work.F` to `work_mod.F` and update the list in `src/Makefile`? 

Thanks!
Dafydd

**Comment by nmolem** [comment]
I'll make a fix and let you know. It is not intentional, but didn't lead to a problem for ifort.

**Comment by nmolem** [comment]
This fix is included in the current state of main. Let me know if it's still a problem, but if not, we can close this.
